root: true
env:
  node: true
  es6: true
  browser: true
extends:
  - "next/core-web-vitals"
  - airbnb
  - airbnb-typescript
  - plugin:@next/next/recommended
  - prettier
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    parserOptions:
      project: ["tsconfig.json"]
rules:
  no-html-link-for-pages: 0
  import/prefer-default-export: 0
  react/react-in-jsx-scope: 0
  react/destructuring-assignment: 0
