name: GoLang CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build
        run: go build -v ./...

      # - name: Run tests
      #   run: go test -v ./...

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to staging environment
  #       run: |
  #         # Add your deployment script or commands here
  #         echo "Deploying to staging environment"
  #         # Example: Deploy to a cloud platform like AWS or Heroku

  # deploy_production:
  #   needs: deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to production environment
  #       run: |
  #         # Add your deployment script or commands here
  #         echo "Deploying to production environment"
  #         # Example: Deploy to a cloud platform like AWS or Heroku
