name: GoLang CI/CD

on:
  pull_request:
    branches:
      - dev

jobs:
  build-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Go modules
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.5"
          check-latest: true
      - name: Test
        run: go test
      - name: Build
        run: go build -o ./dist/server

